### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by jhaynie** [paulogr/dstatuspage#5]
Really cool idea ... Trying to play around with it.

`Node version: v9.5.0`

Starts up fine. 

Seems to load the initial web page fine.

Try and create a test instance.

JS error in the console.

![screen shot 2018-02-05 at 4 56 40 pm 2](https://user-images.githubusercontent.com/6027/35836570-ce4e773c-0a95-11e8-8adf-9e4fced3957b.png)

Any ideas?

**Comment by paulogr** [comment]
Hi, thanks for bring it up!

I was able to reproduce this error, it's a browser specific error only happens on Safari.

I will submit a PR this weekend to fix it.
